/**
 * Image adapter — handles `create_image` actions in the execution manifest.
 *
 * For every create_image action it receives:
 *   1. Calls the configured ImageGenerationProvider with the action's prompt
 *      and dimensions
 *   2. Writes the resulting URL back into the action's payload.resultUrl
 *      (so downstream adapters — the WP adapter, the document adapter —
 *      know where the image lives)
 *   3. Returns an ApplyResult with the externalUrl set
 *
 * Mock mode (default) writes a placeholder image URL from placehold.co —
 * lets us see end-to-end behaviour without paying any provider. Real
 * providers slot in via IMAGE_GENERATION_PROVIDER env var on @rynk/core's
 * factory — no changes here.
 */

import {
  createLogger,
  getImageGenerationProvider,
  type ImageGenerationProvider,
} from "@rynk/core";
import type { CreateImageAction, ExecutionAction } from "@rynk/layer3-generate";
import type { ActionAdapter, ApplyResult } from "../types.js";

const log = createLogger("layer4.image");

/** Map create_image purposes to style hints for the provider. */
function purposeToStyle(purpose: CreateImageAction["target"]["purpose"]): "photo" | "illustration" | "diagram" | "sketch" | "3d" {
  switch (purpose) {
    case "hero":
      return "photo";
    case "inline-diagram":
      return "diagram";
    case "headshot":
      return "photo";
    case "thumbnail":
      return "illustration";
    case "social-card":
      return "illustration";
  }
}

export interface ImageAdapterConfig {
  /** Optional override for the provider (test injection). */
  provider?: ImageGenerationProvider;
}

export function makeImageAdapter(config: ImageAdapterConfig = {}): ActionAdapter {
  const provider = config.provider ?? getImageGenerationProvider();

  return {
    adapterName: `image:${provider.providerName}`,
    channel: "image",

    canHandle(action: ExecutionAction): boolean {
      return action.type === "create_image";
    },

    async apply(action: ExecutionAction): Promise<ApplyResult> {
      // Narrow the type via the discriminator
      if (action.type !== "create_image") {
        return { status: "skipped", message: "Not a create_image action" };
      }

      try {
        const result = await provider.generate({
          prompt: action.payload.prompt,
          width: action.payload.width,
          height: action.payload.height,
          style: purposeToStyle(action.target.purpose),
        });

        // Write the result back into the action so downstream adapters can
        // reference it. Mutation is intentional: the manifest is the
        // single shared state across the apply pass.
        action.payload.resultUrl = result.url;

        log.info("image generated", {
          actionId: action.id,
          provider: provider.providerName,
          url: result.url,
          width: result.width,
          height: result.height,
          costCents: result.costCents,
        });

        return {
          status: "applied",
          externalRef: result.externalId,
          externalUrl: result.url,
          message: `Generated by ${result.provider}${result.costCents !== null ? ` ($${(result.costCents / 100).toFixed(2)})` : ""}.`,
        };
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        log.error("image generation failed", { actionId: action.id, error: msg });
        return { status: "failed", error: msg };
      }
    },
  };
}
