/**
 * Code-PR adapter - handles `propose_code_change` actions.
 *
 * Mock mode (default): saves the PR description and the instructions
 * (which are markdown with code snippets / diff hints) to disk as a
 * draft. A human dev reviews, runs the change, and opens the PR
 * themselves.
 *
 * Output layout:
 *   {outputDir}/code-pr/{action.id}-{slug-of-title}.md
 *
 * The draft file contains:
 *   - Repo + suggested branch name
 *   - PR title + description
 *   - The instructions (file paths, diff hints, or a literal patch)
 *   - Suggested reviewers
 *
 * Real-mode future work (CodePrProvider interface):
 *   - GitHub App or PAT
 *   - octokit clone / fork / branch / commit / open PR
 *   - Auto-add reviewers from action.payload.reviewers
 *   - Configurable: open as draft PR vs ready-for-review
 *   - Lints + a CI smoke check before pushing
 *
 * Why mock-first: real PR creation needs write access to the client's
 * repo, signed commits, and the human dev's involvement anyway. The
 * draft-on-disk version is what they'll work from regardless.
 */

import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { createLogger } from "@rynk/core";
import type {
  ExecutionAction,
  ProposeCodeChangeAction,
} from "@rynk/layer3-generate";
import type { ActionAdapter, ApplyResult } from "../types.js";

const log = createLogger("layer4.code-pr");

export interface CodePrAdapterConfig {
  /** Where draft PR markdown files land. Default: ./runs/_drafts/code-pr */
  outputDir?: string;
}

export function makeCodePrAdapter(config: CodePrAdapterConfig = {}): ActionAdapter {
  const outputDir = resolve(config.outputDir ?? "./runs/_drafts/code-pr");

  return {
    adapterName: "code-pr-mock",
    channel: "code-pr",

    canHandle(action: ExecutionAction): boolean {
      return action.type === "propose_code_change";
    },

    async apply(action: ExecutionAction): Promise<ApplyResult> {
      if (action.type !== "propose_code_change") {
        return { status: "skipped", message: "Not a propose_code_change action" };
      }
      const pr = action as ProposeCodeChangeAction;

      try {
        const fileName = `${action.id}-${slug(pr.payload.title)}.md`;
        const filePath = join(outputDir, fileName);
        const content = composePrDraft(pr);

        await writeFileEnsuringDir(filePath, content);

        log.info("code-pr draft saved", {
          actionId: action.id,
          repo: pr.target.repo,
          branch: pr.target.branch,
          filePath,
        });

        return {
          status: "applied",
          externalRef: `${pr.target.repo}#${pr.target.branch}`,
          externalUrl: filePath,
          message: `Code-change draft saved to ${filePath}. Repo: ${pr.target.repo}, suggested branch: ${pr.target.branch}. Mock mode - human opens the actual PR.`,
        };
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        log.error("code-pr draft save failed", { actionId: action.id, error: msg });
        return { status: "failed", error: msg };
      }
    },
  };
}

// ── Helpers ────────────────────────────────────────────────────────────────

async function writeFileEnsuringDir(path: string, content: string): Promise<void> {
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, content, "utf8");
}

function slug(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 50);
}

function composePrDraft(pr: ProposeCodeChangeAction): string {
  const lines: string[] = [
    `# ${pr.payload.title}`,
    "",
    `**Repo:** \`${pr.target.repo}\`  `,
    `**Suggested branch:** \`${pr.target.branch}\`  `,
    `**Action:** \`${pr.id}\`  `,
    `**Risk:** ${pr.risk}`,
    "",
    "## Description",
    "",
    pr.payload.description,
    "",
    "## Instructions",
    "",
    pr.payload.instructions,
    "",
  ];

  if (pr.payload.reviewers.length > 0) {
    lines.push(
      "## Suggested reviewers",
      "",
      ...pr.payload.reviewers.map((r) => `- @${r}`),
      "",
    );
  }

  if (pr.notes) {
    lines.push("## Notes", "", pr.notes, "");
  }

  lines.push(
    "---",
    "",
    `Generated by rynk. Source: \`${pr.provenance.source}\` / \`${pr.provenance.sourceId}\`.`,
    "",
    `Reason: ${pr.provenance.reason}`,
  );

  return lines.join("\n");
}
