/**
 * Document adapter - handles `create_document` actions.
 *
 * For every create_document action:
 *   1. Renders the source markdown into a draft file
 *   2. Saves it under {outputDir}/documents/{action.id}.{ext}
 *   3. Returns ApplyResult with externalUrl pointing at the saved file
 *
 * Mock mode (default) writes the document as a styled HTML file plus the
 * raw markdown. Real PDF / PPTX rendering is future work behind a
 * `DocumentRenderProvider` interface - same pattern as
 * `ImageGenerationProvider`. Swap by env var when real providers land.
 *
 * Why mock-first:
 *   - PDF generation needs Chrome/Puppeteer (heavy dependency)
 *   - PPTX generation needs pptxgenjs and template wrangling
 *   - Demo only requires "the file exists at a path the dashboard can
 *     link to" - we deliver that today; we deliver bytes later.
 *
 * The dashboard will surface a download link to whatever file lands here.
 */

import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { createLogger } from "@rynk/core";
import type {
  CreateDocumentAction,
  ExecutionAction,
} from "@rynk/layer3-generate";
import type { ActionAdapter, ApplyResult } from "../types.js";

const log = createLogger("layer4.document");

export interface DocumentAdapterConfig {
  /** Where draft files land. Default: ./runs/_drafts/documents */
  outputDir?: string;
}

export function makeDocumentAdapter(config: DocumentAdapterConfig = {}): ActionAdapter {
  const outputDir = resolve(config.outputDir ?? "./runs/_drafts/documents");

  return {
    adapterName: "document-mock",
    channel: "document",

    canHandle(action: ExecutionAction): boolean {
      return action.type === "create_document";
    },

    async apply(action: ExecutionAction): Promise<ApplyResult> {
      if (action.type !== "create_document") {
        return { status: "skipped", message: "Not a create_document action" };
      }
      const doc = action as CreateDocumentAction;

      try {
        const baseName = `${action.id}-${slugifyForFile(doc.payload.title)}`;
        const mdPath = join(outputDir, `${baseName}.md`);
        const htmlPath = join(outputDir, `${baseName}.html`);

        // 1. Write the raw markdown source so a human can edit / re-render.
        const markdownBody = composeMarkdownDocument(doc);
        await writeFileEnsuringDir(mdPath, markdownBody);

        // 2. Write a styled HTML preview so the file is openable in any
        //    browser - good enough as a stand-in until the real renderer
        //    (PDF / PPTX) is wired.
        const htmlBody = composeHtmlPreview(doc, markdownBody);
        await writeFileEnsuringDir(htmlPath, htmlBody);

        log.info("document draft saved", {
          actionId: action.id,
          docType: doc.target.docType,
          format: doc.target.format,
          mdPath,
          htmlPath,
        });

        return {
          status: "applied",
          externalRef: baseName,
          externalUrl: htmlPath,
          message: `${doc.target.format.toUpperCase()} draft saved (mock renderer - real ${doc.target.format} rendering pending). Markdown: ${mdPath}, HTML preview: ${htmlPath}`,
        };
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        log.error("document save failed", { actionId: action.id, error: msg });
        return { status: "failed", error: msg };
      }
    },
  };
}

// ── Helpers ────────────────────────────────────────────────────────────────

async function writeFileEnsuringDir(path: string, content: string): Promise<void> {
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, content, "utf8");
}

function slugifyForFile(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60);
}

/**
 * Assemble the markdown body for the draft file. Title + source pointer +
 * the LLM-generated body + provenance footer for the reviewer.
 */
function composeMarkdownDocument(doc: CreateDocumentAction): string {
  const lines: string[] = [
    `# ${doc.payload.title}`,
    "",
  ];

  if (doc.payload.sourceContentUrl) {
    lines.push(`> Source content: ${doc.payload.sourceContentUrl}`, "");
  }

  lines.push(doc.payload.bodyMarkdown, "");

  if (doc.payload.distributionPlatforms.length > 0) {
    lines.push(
      "---",
      "",
      "**Distribution targets:** " + doc.payload.distributionPlatforms.join(", "),
      "",
    );
  }

  // Provenance footer (small print).
  lines.push(
    "---",
    "",
    `Generated by rynk for action \`${doc.id}\`.  `,
    `Target format: ${doc.target.format.toUpperCase()}. Document type: ${doc.target.docType}.`,
  );
  return lines.join("\n");
}

/**
 * Wrap the markdown in a minimal but readable HTML preview so it can be
 * opened directly in a browser (or "Print to PDF" for a quick PDF in
 * mock mode). Not pretty enough to ship to a client, but enough to
 * eyeball the structure during dev.
 */
function composeHtmlPreview(doc: CreateDocumentAction, markdown: string): string {
  const escaped = markdown
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
  return [
    "<!doctype html>",
    `<html lang="en"><head>`,
    `<meta charset="utf-8">`,
    `<title>${doc.payload.title}</title>`,
    `<style>`,
    `body{font:16px/1.55 -apple-system,BlinkMacSystemFont,Segoe UI,Roboto,sans-serif;max-width:780px;margin:48px auto;padding:0 24px;color:#1f2937;}`,
    `h1{font-size:32px;margin-bottom:8px;}h2{font-size:22px;margin-top:32px;}`,
    `pre{white-space:pre-wrap;font-family:inherit;background:#f9fafb;padding:24px;border-radius:8px;border:1px solid #e5e7eb;}`,
    `.meta{color:#6b7280;font-size:13px;margin-bottom:32px;}`,
    `</style></head><body>`,
    `<p class="meta">${doc.target.format.toUpperCase()} draft &middot; ${doc.target.docType} &middot; action ${doc.id}</p>`,
    `<pre>${escaped}</pre>`,
    `</body></html>`,
  ].join("\n");
}
