/**
 * Social adapter - handles `draft_brand_post` actions.
 *
 * Mock mode (default): saves each draft post to disk as a markdown file
 * the human can copy-paste into LinkedIn / Reddit / Threads etc. We do
 * NOT auto-post - brand posts are intentionally human-gated per the
 * action schema doc string.
 *
 * Output layout:
 *   {outputDir}/social/{platform}/{action.id}.md
 *
 * Each file contains the post body, suggested publish date, rationale,
 * and any attached image action references so the publisher knows what
 * media to include.
 *
 * Real-mode future work:
 *   - LinkedIn API (OAuth + developer program approval needed)
 *   - Reddit API (PRAW-style)
 *   - Threads API (still rolling out)
 *   - Each goes behind a SocialPostProvider interface keyed by platform.
 */

import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { createLogger } from "@rynk/core";
import type {
  DraftBrandPostAction,
  ExecutionAction,
} from "@rynk/layer3-generate";
import type { ActionAdapter, ApplyResult } from "../types.js";

const log = createLogger("layer4.social");

export interface SocialAdapterConfig {
  /** Where draft posts land. Default: ./runs/_drafts/social */
  outputDir?: string;
}

export function makeSocialAdapter(config: SocialAdapterConfig = {}): ActionAdapter {
  const outputDir = resolve(config.outputDir ?? "./runs/_drafts/social");

  return {
    adapterName: "social-mock",
    channel: "social",

    canHandle(action: ExecutionAction): boolean {
      return action.type === "draft_brand_post";
    },

    async apply(action: ExecutionAction): Promise<ApplyResult> {
      if (action.type !== "draft_brand_post") {
        return { status: "skipped", message: "Not a draft_brand_post action" };
      }
      const post = action as DraftBrandPostAction;

      try {
        const platform = post.target.platform;
        const sub = post.target.subPlatform ? `-${slug(post.target.subPlatform)}` : "";
        const filePath = join(outputDir, platform, `${action.id}${sub}.md`);
        const content = composeBrandPostDraft(post);

        await writeFileEnsuringDir(filePath, content);

        log.info("social draft saved", {
          actionId: action.id,
          platform,
          subPlatform: post.target.subPlatform ?? null,
          filePath,
        });

        return {
          status: "applied",
          externalRef: `${platform}:${action.id}`,
          externalUrl: filePath,
          message: `Brand post drafted for ${platform}${post.target.subPlatform ? ` / ${post.target.subPlatform}` : ""}. Saved to ${filePath}. NOT auto-posted - human publishes from their own account.`,
        };
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        log.error("social draft save failed", { actionId: action.id, error: msg });
        return { status: "failed", error: msg };
      }
    },
  };
}

// ── Helpers ────────────────────────────────────────────────────────────────

async function writeFileEnsuringDir(path: string, content: string): Promise<void> {
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, content, "utf8");
}

function slug(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 40);
}

function composeBrandPostDraft(post: DraftBrandPostAction): string {
  const lines: string[] = [
    `# Brand post draft - ${post.target.platform}${post.target.subPlatform ? ` / ${post.target.subPlatform}` : ""}`,
    "",
    `**Action:** \`${post.id}\``,
    `**Suggested publish date:** ${post.payload.suggestedPublishDate ?? "ASAP"}`,
    "",
    "## Body (copy to your platform composer)",
    "",
    post.payload.body,
    "",
    "## Why this post",
    "",
    post.payload.rationale,
    "",
  ];

  if (post.payload.imageActionIds.length > 0) {
    lines.push(
      "## Attach these image action results",
      "",
      ...post.payload.imageActionIds.map((id) => `- \`${id}\``),
      "",
    );
  }

  if (post.notes) {
    lines.push("## Notes", "", post.notes, "");
  }

  lines.push(
    "---",
    "",
    `Generated by rynk. Source: \`${post.provenance.source}\` / \`${post.provenance.sourceId}\`.`,
  );

  return lines.join("\n");
}
