/**
 * Matrix verifier - runs the same battery of Layer 4 handlers against
 * multiple local WordPress configurations and prints a grid showing
 * what each cell produces (applied / skipped / failed) plus any edge
 * case codes.
 *
 * Reads credentials + URLs from each config's local-wp-matrix/{config}/
 * .secrets/config.json (generated by the init container when you bring
 * the config up).
 *
 * Usage from repo root:
 *
 *   npx tsx scripts/verify-matrix.ts
 *
 * Or a single config:
 *
 *   npx tsx scripts/verify-matrix.ts --config baseline
 *
 * The runner tolerates configs that aren't up (missing config.json is
 * treated as "not started - skipping"). Point is to run whichever configs
 * you happen to have brought up, not to require all of them at once.
 */

import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import { makeWordPressAdapter } from "@rynk/layer4-publish";
import type { ExecutionAction } from "@rynk/layer3-generate";

// ── Config discovery ──────────────────────────────────────────────────

interface MatrixConfig {
  config: string;
  url: string;
  user: string;
  appPassword: string;
  testPage: string;
  /** Set by the elementor config - a page carrying `_elementor_edit_mode`. */
  elementorPage?: string;
  elementorPageId?: string;
  /** Set by the divi config - a page carrying `_et_pb_use_builder`. */
  diviPage?: string;
  diviPageId?: string;
  /** Set by the redirection config - a fake source path to redirect. */
  redirectSource?: string;
  /** Set by the woocommerce config - a WooCommerce product URL. */
  productPage?: string;
  productId?: string;
}

const ALL_CONFIGS = [
  "baseline",
  "yoast",
  "rank-math",
  "seopress",
  "elementor",
  "divi",
  "redirection",
  "litespeed",
  "woocommerce",
] as const;

function loadConfig(name: string): MatrixConfig | null {
  const path = resolve("local-wp-matrix", name, ".secrets", "config.json");
  if (!existsSync(path)) return null;
  try {
    const raw = readFileSync(path, "utf8");
    return JSON.parse(raw) as MatrixConfig;
  } catch {
    return null;
  }
}

// ── Test battery ──────────────────────────────────────────────────────

/**
 * Each entry defines one handler to exercise + a builder for the action
 * scoped to a particular config's URLs. When `useElementorPage` is true
 * and the config has an Elementor page, the action targets that page
 * instead of the standard test page. That's how we exercise the skip
 * guard - only the Elementor config will actually route it that way.
 */
interface BatteryEntry {
  key: string;
  buildAction: (cfg: MatrixConfig) => ExecutionAction | null;
}

const baseProv = (sourceId: string, reason: string) => ({
  source: "audit-issue" as const,
  sourceId,
  reason,
});

const BATTERY: BatteryEntry[] = [
  {
    key: "update_meta",
    buildAction: (cfg) =>
      ({
        id: `mx-meta-${cfg.config}`,
        type: "update_meta",
        status: "approved",
        risk: "low",
        channel: "cms",
        automatable: true,
        provenance: baseProv("matrix:meta", "matrix verifier"),
        notes: null,
        target: { url: cfg.testPage },
        payload: {
          title: `rynk matrix ${cfg.config}`,
          metaDescription: `Matrix run against ${cfg.config}.`,
          canonical: null,
          metaRobots: null,
        },
      } as unknown as ExecutionAction),
  },
  {
    key: "inject_schema",
    buildAction: (cfg) =>
      ({
        id: `mx-schema-${cfg.config}`,
        type: "inject_schema",
        status: "approved",
        risk: "low",
        channel: "cms",
        automatable: true,
        provenance: baseProv("matrix:schema", "matrix verifier"),
        notes: null,
        target: { url: cfg.testPage, schemaType: "Organization", location: "page" },
        payload: {
          jsonLd: {
            "@context": "https://schema.org",
            "@type": "Organization",
            name: `Matrix ${cfg.config}`,
          },
        },
      } as unknown as ExecutionAction),
  },
  {
    key: "update_page_on_elementor",
    buildAction: (cfg) =>
      cfg.elementorPage
        ? ({
            id: `mx-updpage-${cfg.config}`,
            type: "update_page",
            status: "approved",
            risk: "low",
            channel: "cms",
            automatable: true,
            provenance: baseProv("matrix:elementor-update", "matrix - expect skip on elementor"),
            notes: null,
            target: { url: cfg.elementorPage, operation: "rewrite" },
            payload: {
              newBodyMarkdown: "Rewritten by matrix",
              addSections: [],
              consolidateFromUrls: [],
            },
          } as unknown as ExecutionAction)
        : null,
  },
  {
    key: "insert_internal_link_on_elementor",
    buildAction: (cfg) =>
      cfg.elementorPage
        ? ({
            id: `mx-link-${cfg.config}`,
            type: "insert_internal_link",
            status: "approved",
            risk: "low",
            channel: "cms",
            automatable: true,
            provenance: baseProv("matrix:elementor-link", "matrix - expect skip on elementor"),
            notes: null,
            target: { sourceUrl: cfg.elementorPage, targetUrl: cfg.testPage },
            payload: { anchorText: "matrix" },
          } as unknown as ExecutionAction)
        : null,
  },
  {
    key: "update_page_on_divi",
    buildAction: (cfg) =>
      cfg.diviPage
        ? ({
            id: `mx-divi-update-${cfg.config}`,
            type: "update_page",
            status: "approved",
            risk: "low",
            channel: "cms",
            automatable: true,
            provenance: baseProv("matrix:divi-update", "matrix - expect skip on divi"),
            notes: null,
            target: { url: cfg.diviPage, operation: "rewrite" },
            payload: {
              newBodyMarkdown: "Rewritten by matrix",
              addSections: [],
              consolidateFromUrls: [],
            },
          } as unknown as ExecutionAction)
        : null,
  },
];

// ── Runner ────────────────────────────────────────────────────────────

interface CellResult {
  status: string;
  edgeCase?: string;
  message?: string;
  error?: string;
}

async function runCell(
  cfg: MatrixConfig,
  entry: BatteryEntry,
): Promise<CellResult | null> {
  const action = entry.buildAction(cfg);
  if (!action) return null;

  process.env["WORDPRESS_LIVE"] = "true";
  const adapter = makeWordPressAdapter({
    siteUrl: cfg.url,
    username: cfg.user,
    appPassword: cfg.appPassword,
  });

  try {
    const result = await adapter.apply(action);
    return {
      status: result.status,
      edgeCase: result.edgeCase,
      message: result.message,
      error: result.error,
    };
  } catch (err) {
    return {
      status: "error",
      error: err instanceof Error ? err.message : String(err),
    };
  }
}

function formatCell(result: CellResult | null | undefined): string {
  if (!result) return "  -  ";
  const short = result.status === "applied"
    ? "PASS"
    : result.status === "skipped"
    ? "SKIP"
    : result.status === "failed" || result.status === "error"
    ? "FAIL"
    : result.status.slice(0, 4).toUpperCase();
  return short;
}

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  const configArgIdx = args.indexOf("--config");
  const specificConfig = configArgIdx !== -1 ? args[configArgIdx + 1] : undefined;

  const requested = specificConfig ? [specificConfig] : ALL_CONFIGS;

  const configs: MatrixConfig[] = [];
  const missing: string[] = [];
  for (const name of requested) {
    const c = loadConfig(name);
    if (c) configs.push(c);
    else missing.push(name);
  }

  if (missing.length > 0) {
    console.log(`\nSkipping (config not up or credentials not generated): ${missing.join(", ")}`);
    console.log(`Bring one up: cd local-wp-matrix/<name> && docker compose up -d\n`);
  }

  if (configs.length === 0) {
    console.log("\nNo configs available to test. Nothing to do.\n");
    process.exit(0);
  }

  // Run every (config x battery entry) cell. Kept sequential so log output
  // stays readable; can be parallelised later once the WP hosts are stable.
  const grid: Record<string, Record<string, CellResult | null>> = {};
  for (const cfg of configs) {
    grid[cfg.config] = {};
    for (const entry of BATTERY) {
      process.stdout.write(`. running ${cfg.config} / ${entry.key}\n`);
      grid[cfg.config]![entry.key] = await runCell(cfg, entry);
    }
  }

  // Print matrix.
  const keyCol = Math.max(...BATTERY.map((e) => e.key.length), 12);
  const configColWidth = Math.max(...configs.map((c) => c.config.length), 8);
  const line = (parts: string[]): string =>
    parts.map((p, i) => (i === 0 ? p.padEnd(keyCol) : p.padEnd(configColWidth))).join("  |  ");

  console.log(`\n=== Matrix results ===\n`);
  console.log(line(["handler", ...configs.map((c) => c.config)]));
  console.log(line(["-".repeat(keyCol), ...configs.map(() => "-".repeat(configColWidth))]));
  for (const entry of BATTERY) {
    const row = [entry.key];
    for (const cfg of configs) {
      row.push(formatCell(grid[cfg.config]?.[entry.key]));
    }
    console.log(line(row));
  }

  // Detail: any FAIL / SKIP with edge codes.
  console.log(`\n=== Details ===`);
  for (const cfg of configs) {
    for (const entry of BATTERY) {
      const r = grid[cfg.config]?.[entry.key];
      if (!r) continue;
      if (r.status !== "applied") {
        const detail = r.edgeCase
          ? `[${r.edgeCase}] ${r.message ?? r.error ?? ""}`
          : (r.message ?? r.error ?? "");
        console.log(`  ${cfg.config}/${entry.key}: ${r.status.toUpperCase()} ${detail}`);
      }
    }
  }

  console.log("");
}

main().catch((err) => {
  console.error("matrix runner failed:", err);
  process.exit(1);
});
