/**
 * Offsite adapter — handles `update_offsite_profile` actions in the
 * execution manifest.
 *
 * Third-party platforms (G2, Clutch, Crunchbase, etc.) have no public update
 * APIs. For each action we write a human-readable markdown brief to disk at
 * `{outputDir}/offsite/{platform}/{actionId}.md` for manual application.
 */

import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { createLogger } from "@rynk/core";
import type { ExecutionAction, UpdateOffsiteProfileAction } from "@rynk/layer3-generate";
import type { ActionAdapter, ApplyResult } from "../types.js";

const log = createLogger("layer4.offsite");

export interface OffsiteAdapterConfig {
  /** Root directory for drafted artifacts (e.g. runs/{domain}/publish). */
  outputDir: string;
}

const PLATFORM_LABELS: Record<UpdateOffsiteProfileAction["target"]["platform"], string> = {
  "google-business-profile": "Google Business Profile",
  g2: "G2",
  clutch: "Clutch",
  capterra: "Capterra",
  crunchbase: "Crunchbase",
  linkedin: "LinkedIn",
  wikidata: "Wikidata",
  bbb: "BBB",
};

function humanizeFieldName(field: string): string {
  return field
    .replace(/_/g, " ")
    .replace(/([a-z])([A-Z])/g, "$1 $2")
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

/** Assemble a markdown brief a human can follow when logged into the platform. */
export function composeOffsiteProfileDraft(action: UpdateOffsiteProfileAction): string {
  const { platform, profileUrl } = action.target;
  const label = PLATFORM_LABELS[platform];
  const lines: string[] = [
    `# ${label} Profile Update`,
    "",
    "> **Manual update required.** Log into the platform and apply the changes below.",
    "> This file was generated by rynk — nothing was posted automatically.",
    "",
    `**Platform:** ${label}`,
  ];

  if (profileUrl) {
    lines.push(`**Profile URL:** ${profileUrl}`);
  }
  lines.push(`**Action ID:** ${action.id}`, "", "---", "");

  lines.push("## Why this change helps", "", action.provenance.reason, "");

  lines.push("## Instructions", "", action.payload.instructions, "");

  lines.push("## Proposed updates", "");
  for (const [field, proposed] of Object.entries(action.payload.fieldsToUpdate)) {
    lines.push(
      `### ${humanizeFieldName(field)}`,
      "",
      "**Current state:** _(verify on platform — not captured in audit)_",
      "",
      "**Proposed:**",
      "",
      proposed,
      "",
    );
  }

  if (action.notes) {
    lines.push("---", "", "## Notes", "", action.notes, "");
  }

  return lines.join("\n").trimEnd() + "\n";
}

export function makeOffsiteAdapter(config: OffsiteAdapterConfig): ActionAdapter {
  const { outputDir } = config;

  return {
    adapterName: "offsite",
    channel: "offsite",

    canHandle(action: ExecutionAction): boolean {
      return action.type === "update_offsite_profile";
    },

    async apply(action: ExecutionAction): Promise<ApplyResult> {
      if (action.type !== "update_offsite_profile") {
        return { status: "skipped", message: "Not an update_offsite_profile action" };
      }

      const update = action as UpdateOffsiteProfileAction;
      const dir = join(outputDir, "offsite", update.target.platform);
      const filePath = join(dir, `${update.id}.md`);

      try {
        await mkdir(dir, { recursive: true });
        await writeFile(filePath, composeOffsiteProfileDraft(update), "utf8");

        log.info("offsite profile draft written", {
          actionId: update.id,
          platform: update.target.platform,
          filePath,
        });

        return {
          status: "applied",
          externalUrl: filePath,
          message: `Draft saved to ${filePath}. Update was NOT applied — log into ${PLATFORM_LABELS[update.target.platform]} and apply manually.`,
        };
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        log.error("offsite profile draft failed", { actionId: update.id, error: msg });
        return { status: "failed", error: msg };
      }
    },
  };
}
