import {type SerpDelta, type SerpSnapshot, } from "@rynk/layer5-monitor/schema";
import { readJson, createLogger } from "@rynk/core/utils"
import { ClientContext, moduleDir } from "@rynk/core";
import { runStrategyAgent, loadAuditInput, saveStrategyOutput } from "@rynk/layer2-strategy";
import { resolve } from "node:path";


const DEFAULT_AUDIT = "./inputs/itechdata-seo-eeat-audit.md";
const OUTPUT_ROOT = resolve(moduleDir(import.meta.url), "../../../runs");



const log = createLogger("layer5.restrategy-trigger")

export async function maybeTriggerRestrategy( delta: SerpDelta, clientContext: ClientContext, runsDir: string,): Promise<{ triggered: boolean; runId: string | null }> {
    
    //if there's no reason to trigger restrategy, return from the function immediately
    if(!delta.triggerRestrategy) return { triggered: false, runId: null}

    const auditPath = process.argv[2] ?? DEFAULT_AUDIT;

    log.info("starting Layer 2 — Strategy Agent");

    const audit = loadAuditInput(auditPath);
    log.info("audit loaded", { path: auditPath, format: audit.format, chars: audit.content.length });

    const strategy = await runStrategyAgent({ audit, clientContext });

    const { jsonPath, mdPath } = saveStrategyOutput(strategy, OUTPUT_ROOT);
    log.info("Layer 2 complete", { jsonPath, mdPath });

    process.stdout.write(`\nStrategy generated.\n  JSON: ${jsonPath}\n  MD:   ${mdPath}\n\n`);
    runStrategyAgent({audit, clientContext})

    //runId should be a UUID generated by the DB

    log.warn("Partial strategy doesn't exist. Run ID generation doesn't exist.")
    let UUID = null
    return { triggered: true, runId: UUID }
}